apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample-app
  template:
    metadata:
      labels:
        app: eks-sample-app
    spec:
      containers:
      - name: eks-sample-app
        image: <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/eks-sample-app:latest
        ports:
        - containerPort: 3000
